name: Test
on: push
jobs:
    test:
        name: test
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            
            - uses: conda-incubator/setup-miniconda@v2
              with:
                auto-update-conda: true
                python-version: 3.11

            - run: conda install numpy gdal requests

            - run: conda list 

            - shell: python
              run: |
                import threading
                import subprocess
                
                import numpy
                import requests
                from osgeo import gdal
                
                gdal.GetDriverByName('GTiff').Create('test.tif', 1, 1)
                
                for _ in range(164):  # the seg fault does not happen with fewer than 164 threads
                    thread = threading.Thread(
                        target=gdal.OpenEx,
                        args=('test.tif',))
                    thread.start()
                    thread.join()
                
                requests.get('https://example.com')
                subprocess.run(['pwd'])
              
